repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5 # Use the latest version
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^backend/.*\.py$ # Only backend Python files

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        files: ^backend/.*\.py$ # Format Python code

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/prettier/prettier
    rev: 3.3.3
    hooks:
      - id: prettier
        files: ^frontend/.*\.(js|jsx|ts|tsx|css|json|md)$ # Frontend files
