version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - supabase  # Assuming Supabase is local; in prod, use cloud

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # Optional: Local Supabase for dev
  supabase:
    image: supabase/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - supabase_data:/var/lib/postgresql/data

volumes:
  supabase_data:
